'''
Adicione o módulo moeda.py criado nos desafios anteriores, uma função chamada resumo(), que mostre na tela algumas
informações geradas pelas funções que já temos no módulo criado até aqui.

Add the coin.py module created in the previous challenges, a function called summary(), which shows some on the screen.
information generated by the functions we already have in the module created so far.
'''
from modulo import moeda

p = float(input('Informe um preço: R$ '))

moeda.resumo(p, 80, 30)

